// pages/index.tsx
import withAuth from "./components/withAuth";
import Head from "next/head";
import Link from "next/link";
import axios from "axios";

interface HomeProps {
  genres: string[];
}

const Home = ({ genres }: HomeProps) => {
  return (
    <div className="container">
      <Head>
        <title>Music Recommender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Music Recommender</h1>
        <h2>Recommended Artists</h2>
      </main>
      <aside>
        <h2>Genre List</h2>
        <ul>
          {genres.map((genre) => (
            <li key={genre}>
              <Link href={`/${genre}`}>{genre}</Link>
            </li>
          ))}
        </ul>
      </aside>
    </div>
  );
};

export async function getStaticProps() {
  const token = process.env.SPOTIFY_CLIENT_ID; // Use actual token fetching here

  try {
    const response = await axios.get(
      "https://api.spotify.com/v1/recommendations/available-genre-seeds",
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );

    return {
      props: {
        genres: response.data.genres,
      },
      revalidate: 60,
    };
  } catch (error) {
    console.error("Failed to fetch genres from Spotify:", error);
    return {
      props: {
        genres: [],
      },
    };
  }
}

export default withAuth(Home);
